name: Tests
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: "0 15 * * 1-5"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sendgrid-oai
        uses: actions/checkout@v2

      - name: Lint with Spectral
        uses: stoplightio/spectral-action@v0.8.0
        with:
          file_glob: "oai*.{json,yml,yaml}"
